### ISSUE TITLE
Question Regarding Adding Additional Button Links

### ISSUE THREAD

**Issue by RockerGal-Goes-Techie** [migueravila/Bento#59]
Hi there!

I am in the process of editing my startpage and was testing out how I could create more than the six button links that are included in the code to no avail. _**Is there a way where I can add additional button links other than the six that are included?**_

Any assistance is highly appreciated and I thank you in advance!

**Comment by eliyya** [comment]
It seems that it is not fully adapted to add another button, however I added 3 more by changing the `config.js` and 2 lines of `app.css` 
in the config.js there is no loss, it is simply adding another element to `cards` just like the ones it already includes:
```js
{
    id: '7',
    name: 'Telegram',
    icon: 'send',
    ink: 'https://webk.telegram.org/',
}
```
the icons can be found in [lucide.dev](https://lucide.dev/)
in the `app.css` just disable the `grid-template-rows` to have more than those set and modify the` padding` to have more space in the `.buttons` class.
something like this remains:
```css
.buttons {
    grid-row: 3 / span 2;
    grid-column: 1 / span 2;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    /* grid-template-rows: repeat(2, 1fr); */
    grid-gap: 30px;
    padding: 0 20px;
}
```
To add another 3 there is nothing bad.
