### ISSUE TITLE
Custom colors for each list / button

### ISSUE THREAD

**Issue by garevans** [migueravila/Bento#86]
On the previous version of bento, I was able to duplicate the css entry for .qlist__link to .qlist__greenlink, bluelink etc to allow me to have different colour highlight for the two lists.

The new system appears to only allow you to edit the color for all items

**Comment by lewisdoesstuff** [comment]
You're able to edit the style for the individual lists, it's in `app.css`

```css

.list__1 {
  grid-column: 1;
  grid-row: 1 / span 2;
}

.list__2 {
  grid-column: 2;
  grid-row: 1 / span 2;
}

```
I don't think you can change the color of each item in the list, though.
